#!/bin/bash -e

./tinted-builder-rust build base16/templates/swatch -s base16/schemes
./tinted-builder-rust build base16/templates/highlight-js -s base16/schemes
./tinted-builder-rust build base16/templates/tinted-sublime-text -s base16/schemes
./tinted-builder-rust build base16/templates/base16-textmate -s base16/schemes